# Generated by Django 3.1.4 on 2021-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210117_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Abobe Link To Read Post...', max_length=255),
        ),
    ]
